name: Build
on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [windows, ubuntu, macos]
        include:
          - os: windows
            ext: .exe
          - os: macos
            ext: .app
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build the files
        run: |
          g++ hello.cpp -o hello${{ matrix.ext }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-executable
          path: hello${{ matrix.ext }}
          retention-days: 1
  test:
    strategy:
      matrix:
        os: [windows, ubuntu, macos]
        include:
          - os: windows
            ext: .exe
          - os: macos
            ext: .app
    runs-on: ${{ matrix.os }}-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.os }}-executable
      - name: Test
        run: |
          chmod 755 ./hello${{ matrix.ext }}
          ./hello${{ matrix.ext }}
