name: Build 
on: [push]
jobs:
  Build_Cpp_linux:
    name: Build C++ Linux
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build the files
        run: |
          g++ hello.cpp -o hello
      - uses: actions/upload-artifact@v4
        with:
          name: linux-executable
          path: hello
          retention-days: 1
  Build_Cpp_windows:
    name: Build C++ Windows
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build the files
        run: |
          g++ hello.cpp -o hello.exe
      - uses: actions/upload-artifact@v4
        with:
          name: eindows-executable
          path: hello.exe
          retention-days: 1
